create sequence if not exists public.tour_departure_code_seq;
create or replace function public.normalize_tour_modality(value text) returns text language sql immutable security invoker set search_path=public as $$ select case when lower(coalesce(value,'')) like '%priv%' and lower(coalesce(value,'')) not like '%semi%' then 'privado' when lower(coalesce(value,'')) like '%semi%' then 'semiprivado' when lower(coalesce(value,'')) ~ '(regular|shared|compart|low)' then 'regular' else 'regular' end $$;
alter table public.tour_departures add column if not exists departure_code text,add column if not exists product_catalog_id uuid references public.product_catalog(id) on delete set null,add column if not exists modality text,add column if not exists end_time time;
alter table public.tour_departures alter column departure_code set default ('TOUR-'||lpad(nextval('public.tour_departure_code_seq')::text,6,'0'));
update public.tour_departures set departure_code='TOUR-'||lpad(nextval('public.tour_departure_code_seq')::text,6,'0') where nullif(btrim(departure_code),'') is null;
update public.tour_departures set modality=public.normalize_tour_modality(modality) where modality is null or modality not in ('regular','semiprivado','privado');
alter table public.tour_departures alter column departure_code set not null,alter column modality set default 'regular',alter column modality set not null;
drop index if exists public.tour_departures_unique_slot_idx;
create unique index if not exists tour_departures_departure_code_uidx on public.tour_departures(departure_code);
create index if not exists tour_departures_sellable_idx on public.tour_departures(service_date,status,modality);
create index if not exists tour_departures_product_catalog_idx on public.tour_departures(product_catalog_id);
create index if not exists tour_departures_created_by_idx on public.tour_departures(created_by);
alter table public.tour_departures drop constraint if exists tour_departures_modality_check;
alter table public.tour_departures add constraint tour_departures_modality_check check(modality in ('regular','semiprivado','privado'));
alter table public.tour_departures drop constraint if exists tour_departures_status_check;
alter table public.tour_departures add constraint tour_departures_status_check check(status in ('open','closed','completed','cancelled'));

create or replace function public.normalize_booking_inventory() returns trigger language plpgsql security definer set search_path=public as $$
declare v_capacity integer;v_status text;v_date date;v_tour_id text;v_modality text;v_reserved integer;v_channel text;
begin
 if new.sales_channel is null or btrim(new.sales_channel)='' then select nullif(btrim(canal),'') into v_channel from public.leads where id=new.lead_id;new.sales_channel:=coalesce(v_channel,'Directo');end if;
 if new.estado_operacion='Cancelado' then new.booking_status:='cancelled';elsif new.estado_operacion='Completado' and new.booking_status not in ('cancelled','expired') then new.booking_status:='completed';end if;
 if new.booking_status='hold' then if new.hold_expires_at is null then new.hold_expires_at:=now()+interval '15 minutes';end if;else new.hold_expires_at:=null;end if;
 if new.departure_id is null and new.booking_status in ('confirmed','completed') and new.fecha_servicio is not null and nullif(btrim(new.tour_id),'') is not null then
  insert into public.tour_departures(tour_id,product_catalog_id,product_name,service_date,start_time,capacity_total,status,modality,created_by)
  values(new.tour_id,new.product_catalog_id,new.producto,new.fecha_servicio,new.hora_inicio,case when public.normalize_tour_modality(new.modality)='privado' then greatest(coalesce(new.numero_pax,1),1) else 0 end,case when new.booking_status='completed' then 'completed' else 'open' end,public.normalize_tour_modality(new.modality),auth.uid()) returning id into new.departure_id;
 end if;
 if new.departure_id is null or new.booking_status not in ('hold','confirmed') then return new;end if;if new.booking_status='hold' and new.hold_expires_at<=now() then return new;end if;
 select capacity_total,status,service_date,tour_id,modality into v_capacity,v_status,v_date,v_tour_id,v_modality from public.tour_departures where id=new.departure_id;
 if not found then raise exception 'La salida seleccionada no existe.';end if;if v_status<>'open' then raise exception 'La salida seleccionada no está abierta para reservas.';end if;
 if new.fecha_servicio is not null and new.fecha_servicio<>v_date then raise exception 'La fecha del servicio no coincide con la salida.';end if;
 if nullif(btrim(new.tour_id),'') is not null and new.tour_id<>v_tour_id then raise exception 'El producto del servicio no coincide con la salida.';end if;
 if public.normalize_tour_modality(new.modality)<>v_modality then raise exception 'La modalidad de la reserva no coincide con la salida.';end if;
 select coalesce(sum(numero_pax),0)::integer into v_reserved from public.lead_services where departure_id=new.departure_id and (new.id is null or id<>new.id) and (booking_status='confirmed' or (booking_status='hold' and (hold_expires_at is null or hold_expires_at>now())));
 if v_capacity>0 and v_reserved+greatest(coalesce(new.numero_pax,0),0)>v_capacity then raise exception 'No hay cupos suficientes. Capacidad %, ocupados %, solicitados %.',v_capacity,v_reserved,new.numero_pax;end if;return new;
end;$$;

do $$declare row record;v_departure uuid;begin for row in select * from public.lead_services where departure_id is null and booking_status in ('confirmed','completed') and fecha_servicio is not null and nullif(btrim(tour_id),'') is not null order by created_at,id loop
 insert into public.tour_departures(tour_id,product_catalog_id,product_name,service_date,start_time,capacity_total,status,modality,created_by,created_at,updated_at) values(row.tour_id,row.product_catalog_id,row.producto,row.fecha_servicio,row.hora_inicio,case when public.normalize_tour_modality(row.modality)='privado' then greatest(coalesce(row.numero_pax,1),1) else 0 end,case when row.booking_status='completed' then 'completed' else 'open' end,public.normalize_tour_modality(row.modality),row.operation_handoff_by,row.created_at,now()) returning id into v_departure;update public.lead_services set departure_id=v_departure,updated_at=now() where id=row.id;end loop;end$$;

create table if not exists public.tour_departure_resources(id uuid primary key default gen_random_uuid(),departure_id uuid not null references public.tour_departures(id) on delete cascade,resource_id uuid not null references public.operational_resources(id) on delete restrict,quantity integer not null default 1 check(quantity>0),notes text,fulfillment_status text not null default 'Pendiente' check(fulfillment_status in ('Pendiente','Preparado','Entregado')),prepared_at timestamptz,delivered_at timestamptz,created_by uuid references auth.users(id) on delete set null default auth.uid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(departure_id,resource_id));
create index if not exists tour_departure_resources_departure_idx on public.tour_departure_resources(departure_id);create index if not exists tour_departure_resources_resource_idx on public.tour_departure_resources(resource_id);create index if not exists tour_departure_resources_created_by_idx on public.tour_departure_resources(created_by);
drop trigger if exists trg_sync_tour_resource_fulfillment on public.tour_departure_resources;create trigger trg_sync_tour_resource_fulfillment before update of fulfillment_status on public.tour_departure_resources for each row execute function public.sync_resource_fulfillment_timestamps();
insert into public.tour_departure_resources(departure_id,resource_id,quantity,notes,fulfillment_status,prepared_at,delivered_at) select ls.departure_id,sra.resource_id,sum(sra.quantity)::integer,nullif(string_agg(distinct nullif(btrim(sra.notes),''),' · '),'') ,case when bool_and(sra.fulfillment_status='Entregado') then 'Entregado' when bool_or(sra.fulfillment_status in ('Preparado','Entregado')) then 'Preparado' else 'Pendiente' end,max(sra.prepared_at),max(sra.delivered_at) from public.service_resource_assignments sra join public.lead_services ls on ls.id=sra.lead_service_id where ls.departure_id is not null group by ls.departure_id,sra.resource_id on conflict(departure_id,resource_id) do nothing;
create table if not exists public.tour_departure_notes(id uuid primary key default gen_random_uuid(),departure_id uuid not null references public.tour_departures(id) on delete cascade,source text not null default 'operations' check(source in ('sales','operations','system')),note text not null check(nullif(btrim(note),'') is not null),created_by uuid references auth.users(id) on delete set null default auth.uid(),created_at timestamptz not null default now());
create index if not exists tour_departure_notes_departure_idx on public.tour_departure_notes(departure_id,created_at desc);create index if not exists tour_departure_notes_created_by_idx on public.tour_departure_notes(created_by);
alter table public.reservation_documents add column if not exists risk_data jsonb not null default '{}'::jsonb;
alter table public.tour_departure_resources enable row level security;alter table public.tour_departure_notes enable row level security;
drop policy if exists tour_departures_auth_read on public.tour_departures;create policy tour_departures_auth_read on public.tour_departures for select to authenticated using((select public.current_user_role()) is not null);
drop policy if exists tour_departures_auth_insert on public.tour_departures;create policy tour_departures_auth_insert on public.tour_departures for insert to authenticated with check((select public.current_user_role()) in ('admin','manager','agent'));
drop policy if exists tour_departures_auth_update on public.tour_departures;create policy tour_departures_auth_update on public.tour_departures for update to authenticated using((select public.current_user_role()) in ('admin','manager','agent')) with check((select public.current_user_role()) in ('admin','manager','agent'));
drop policy if exists tour_departures_auth_delete on public.tour_departures;create policy tour_departures_auth_delete on public.tour_departures for delete to authenticated using((select public.current_user_role()) in ('admin','manager'));
create policy tour_departure_resources_read on public.tour_departure_resources for select to authenticated using((select public.current_user_role()) is not null);
create policy tour_departure_resources_insert on public.tour_departure_resources for insert to authenticated with check((select public.current_user_role()) in ('admin','manager','agent'));
create policy tour_departure_resources_update on public.tour_departure_resources for update to authenticated using((select public.current_user_role()) in ('admin','manager','agent')) with check((select public.current_user_role()) in ('admin','manager','agent'));
create policy tour_departure_resources_delete on public.tour_departure_resources for delete to authenticated using((select public.current_user_role()) in ('admin','manager','agent'));
create policy tour_departure_notes_read on public.tour_departure_notes for select to authenticated using((select public.current_user_role()) is not null);
create policy tour_departure_notes_insert on public.tour_departure_notes for insert to authenticated with check((select public.current_user_role()) in ('admin','manager','agent') and created_by=(select auth.uid()));
create policy tour_departure_notes_delete on public.tour_departure_notes for delete to authenticated using((select public.current_user_role()) in ('admin','manager'));
grant usage,select on sequence public.tour_departure_code_seq to authenticated;grant select,insert,update,delete on public.tour_departures,public.tour_departure_resources to authenticated;grant select,insert,delete on public.tour_departure_notes to authenticated;

create or replace function public.set_link_service_departures(p_lead_id uuid,p_assignments jsonb) returns jsonb language plpgsql security invoker set search_path=public as $$
declare v_user uuid:=auth.uid();v_role text;v_lead public.leads%rowtype;item jsonb;v_index integer;v_service public.lead_services%rowtype;v_departure public.tour_departures%rowtype;v_count integer:=0;
begin v_role:=public.current_user_role();if v_user is null or v_role not in ('admin','manager','agent') then raise exception 'Not authorized';end if;select * into v_lead from public.leads where id=p_lead_id;if not found then raise exception 'Reserva no encontrada';end if;if v_role='agent' and coalesce(v_lead.assigned_to,v_lead.created_by)<>v_user then raise exception 'No puedes modificar una reserva asignada a otro vendedor';end if;
 for item in select value from jsonb_array_elements(coalesce(p_assignments,'[]'::jsonb)) loop v_index:=coalesce((item->>'service_index')::integer,-1);if v_index<0 or nullif(item->>'departure_id','') is null then continue;end if;select * into v_service from public.lead_services where lead_id=p_lead_id and booking_status='quoted' order by service_code,created_at,id offset v_index limit 1;if not found then raise exception 'Producto cotizado % no encontrado',v_index+1;end if;select * into v_departure from public.tour_departures where id=(item->>'departure_id')::uuid and status='open';if not found then raise exception 'La salida seleccionada ya no está disponible';end if;if v_service.tour_id<>v_departure.tour_id or v_service.fecha_servicio<>v_departure.service_date or public.normalize_tour_modality(v_service.modality)<>v_departure.modality then raise exception 'El producto, fecha o modalidad no coincide con la salida %',v_departure.departure_code;end if;update public.lead_services set departure_id=v_departure.id,updated_at=now() where id=v_service.id;v_count:=v_count+1;end loop;return jsonb_build_object('lead_id',p_lead_id,'assigned_services',v_count);end;$$;
revoke all on function public.set_link_service_departures(uuid,jsonb) from public,anon;grant execute on function public.set_link_service_departures(uuid,jsonb) to authenticated;

create or replace function public.list_sellable_tour_departures(p_from date default current_date,p_to date default current_date+120) returns table(departure_id uuid,departure_code text,tour_id text,product_catalog_id uuid,product_name text,service_date date,start_time time,capacity_total integer,modality text,status text,notes text,confirmed_pax integer,reservation_count integer,available_pax integer,latest_sales_note text) language plpgsql stable security definer set search_path=public as $$
begin if auth.uid() is null or public.current_user_role() not in ('admin','manager','agent','viewer') then raise exception 'Not authorized';end if;return query select d.id,d.departure_code,d.tour_id,d.product_catalog_id,d.product_name,d.service_date,d.start_time,d.capacity_total,d.modality,d.status,d.notes,coalesce(x.confirmed_pax,0),coalesce(x.reservation_count,0),case when d.capacity_total=0 then null else greatest(d.capacity_total-coalesce(x.confirmed_pax,0),0) end,n.note from public.tour_departures d left join lateral(select coalesce(sum(s.numero_pax),0)::integer confirmed_pax,count(distinct s.lead_id)::integer reservation_count from public.lead_services s where s.departure_id=d.id and s.booking_status in ('confirmed','completed'))x on true left join lateral(select dn.note from public.tour_departure_notes dn where dn.departure_id=d.id and dn.source='sales' order by dn.created_at desc limit 1)n on true where d.service_date between coalesce(p_from,current_date) and coalesce(p_to,current_date+120) order by d.service_date,d.start_time nulls last,d.product_name,d.departure_code;end;$$;
revoke all on function public.list_sellable_tour_departures(date,date) from public,anon;grant execute on function public.list_sellable_tour_departures(date,date) to authenticated;
revoke all on function public.normalize_booking_inventory() from public,anon,authenticated;
